
FROM rust:1.71.1 

RUN USER=root apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install git curl g++ build-essential libssl-dev pkg-config libpq-dev && \
    apt-get -y install software-properties-common && \
    apt-get update 

RUN USER=root mkdir twilight-relayerAPI
WORKDIR /twilight-relayerAPI

COPY .env .env
COPY archiver archiver
RUN chmod 600 /twilight-relayerAPI/archiver
RUN chmod +x archiver
EXPOSE 8989
CMD ["/twilight-relayerAPI/archiver"]

