global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Twilight Relayer metrics
  - job_name: "relayer"
    static_configs:
      - targets: ["relayer-dev:3030"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (system metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor (container metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # PostgreSQL metrics (if you add postgres_exporter later)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s

  # Redis metrics (if you add redis_exporter later)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s

  # QuestDB metrics (if available)
  - job_name: "questdb"
    static_configs:
      - targets: ["questdb:9003"]
    scrape_interval: 30s

  # Kafka metrics (if you add kafka_exporter later)
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
    scrape_interval: 30s
